default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5434
  username: rails
  password: rails

development:
  <<: *default
  database: ecom_development

test:
  <<: *default
  database: ecom_test

production:
  <<: *default
  database: ecom_production
  username: ecom
  password: <%= ENV["ECOM_DATABASE_PASSWORD"] %>
