// Entry point for the build script in your package.json
import "@hotwired/turbo-rails"
import "./add_jquery"
import "./controllers"
import * as bootstrap from "bootstrap"
import "trix"
import "@rails/actiontext"
import "./theme.min"
import "./tiny-slider"
import "./tns-slider"
import "./zoom.min"